---
# PLAY 1: Forbered IP'er
- name: "Forbered de valgte IP-adresser"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Tilføj fundne IP'er til midlertidig gruppe"
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: discovered_switches
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_user: "{{ onboard_user }}"
        ansible_password: "{{ onboard_password }}"
      loop: "{{ target_ips.split(',') }}"
      when: target_ips is defined

# PLAY 2: CDP Scanner & NetBox Cable Builder
- name: "CDP Cable Scanner (Topology Sync)"
  hosts: discovered_switches
  gather_facts: no

  vars:
    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_URL') }}"
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"

  tasks:
    - name: "1. Hent Switch Hostname (Lokal Enhed) 🕵️"
      cisco.ios.ios_facts:
        gather_subset: [min]

    - name: "2. Kør 'show cdp neighbors detail' på switchen 📡"
      cisco.ios.ios_command:
        commands: "show cdp neighbors detail"
      register: cdp_raw

    - name: "3. Ekstraher forbindelser via RegEx Magi 🧙‍♂️"
      # Regex leder efter blokke med Device ID, Lokal Interface og Port ID. 
      # (?s) gør at den læser på tværs af linjeskift.
      set_fact:
        cdp_neighbors: >-
          {{ cdp_raw.stdout[0] | regex_findall('(?s)Device ID:\s*([^\n ]+).*?Interface:\s*([a-zA-Z0-9\/]+),\s*Port ID \(outgoing port\):\s*([a-zA-Z0-9\/]+)') }}
      when: cdp_raw.stdout is defined and cdp_raw.stdout[0] != ""

    - name: "4. Forbind portene med kabler i NetBox 🧵"
      netbox.netbox.netbox_cable:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data:
          status: "connected"
          termination_a_type: "dcim.interface"
          termination_a:
            device: "{{ ansible_net_hostname }}"
            # item[1] er vores Lokal Port (f.eks. GigabitEthernet1/0/1)
            name: "{{ item[1] }}"
          termination_b_type: "dcim.interface"
          termination_b:
            # item[0] er Remote Device. Vi splitter på '.' for at fjerne evt. domæner som .domain.local
            device: "{{ item[0].split('.')[0] }}"
            # item[2] er Remote Port (f.eks. GigabitEthernet1/0/48)
            name: "{{ item[2] }}"
      # Vi looper igennem alle de forbindelser vi fandt
      loop: "{{ cdp_neighbors | default([]) }}"
      delegate_to: localhost
      # Vi ignorerer fejl, for hvis den finder et Access Point eller en IP-telefon, som ikke findes i NetBox endnu, 
      # så skal den bare springe den over og fortsætte med switchene!
      ignore_errors: yes
