---
# PLAY 1: Forbered IP'er
- name: "Forbered de valgte IP-adresser"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Tilføj fundne IP'er til midlertidig gruppe"
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: discovered_switches
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_user: "{{ onboard_user }}"
        ansible_password: "{{ onboard_password }}"
      loop: "{{ target_ips.split(',') }}"
      when: target_ips is defined

# PLAY 2: VLAN & 802.1Q Sync
- name: "Interface Updater (VLAN Sync)"
  hosts: discovered_switches
  gather_facts: no

  vars:
    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_URL') }}"
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"

  tasks:
    - name: "1. Hent Switch Hostname 🕵️"
      cisco.ios.ios_facts:
        gather_subset: [min]

    - name: "2. Hent Layer 2 konfiguration (Access/Trunk) fra Switchen 🧠"
      cisco.ios.ios_l2_interfaces:
        state: gathered
      register: l2_info

    - name: "3. Opdater Access Porte (Untagged VLAN) i NetBox 🟦"
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data:
          device: "{{ ansible_net_hostname }}"
          name: "{{ item.name }}"
          mode: "access"
          # 'untagged_vlan' er NetBox-måden at sige "Access VLAN" på
          untagged_vlan: 
            vid: "{{ item.access.vlan }}"
            site: "{{ target_site }}"
      loop: "{{ l2_info.gathered | default([]) }}"
      when: 
        - item.access is defined
        - item.access.vlan is defined
      delegate_to: localhost
      ignore_errors: yes

    - name: "4. Opdater Trunk Porte (Tagged Mode & Native VLAN) i NetBox 🟪"
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data:
          device: "{{ ansible_net_hostname }}"
          name: "{{ item.name }}"
          mode: "tagged"
          # På en Trunk er Native VLAN det vi kalder for "Untagged"
          untagged_vlan: 
            vid: "{{ item.trunk.native_vlan | default(1) }}"
            site: "{{ target_site }}"
      loop: "{{ l2_info.gathered | default([]) }}"
      when: 
        - item.trunk is defined
      delegate_to: localhost
      ignore_errors: yes
